---
- name: Wait for OpenShift install to complete
  hosts: all
  vars:
    # ocp_base_path: /home/ansible/openshift          # The path to store openshift related data such as install config
                                                      # and openshift-install binary.
    # ocp_config_path: "{{ ocp_base_path }}/config"   # Install config directory used during openshift installation and
                                                      # configuration. The config directory contains the iginition files
                                                      # created by openshift-install and the initial auth credentials for
                                                      # openshift.
    timeout_in_sec: 3060                    # maximal time a long running task is allowed to run before it times out.
                                            # the "openshift-install wait-for install-complete" command runs up to
                                            # 50 minutes before it fails. Hence the timout for the async task is set
                                            # slightly longer: 51 minutes.
    timeout_retry_interval_in_sec: 30       # interval in which ansible checks if the long runnig tasks has finished.
  tasks:
    - name: Run openshift-install wait-for install-complete
      block:
        - name: Run async openshift-install wait-for install-complete
          ansible.builtin.command:
            cmd: "./openshift-install --dir={{ ocp_config_path }} wait-for install-complete --log-level=info"
            chdir: "{{ ocp_base_path }}"
          async: "{{ timeout_in_sec }}"     # The task will only time out if it exceeds the timeout limit you set with
                                            # the async parameter (value in seconds).
          poll: 0                           # When you set poll: 0, Ansible starts the task and immediately moves on to
                                            # the next task without waiting for a result.
          register: ocp_wait_for_install    # More details at: https://docs.ansible.com/ansible/latest/user_guide/playbooks_async.html
          changed_when: false

        - name: Wait for async openshift-install task to finish
          ansible.builtin.async_status:
            jid: "{{ ocp_wait_for_install.ansible_job_id }}"
          register: res_ocp_wait_for_install
          until: res_ocp_wait_for_install.finished
          retries: "{{ (timeout_in_sec / timeout_retry_interval_in_sec * 60) | round(0,'ceil') | int }}"
          delay: "{{ timeout_retry_interval_in_sec }}"
          changed_when: false
      always:
        - name: Print async task details
          ansible.builtin.debug:
            var: res_ocp_wait_for_install
...
